apiVersion: v1
kind: ConfigMap
metadata:
  name: springbootapi-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/tasklistdb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres 
  SPRING_PROFILES_ACTIVE: prod
