apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springbootapi-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: springbootapi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springbootapi-service
                port:
                  number: 8081

