apiVersion: v1
kind: Service
metadata:
  name: springbootapi-service
spec:
  selector:
    app: springbootapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
type: ClusterIP