apiVersion: v1
kind: Service
metadata:
  name: springbootapi-service
  labels:
    app: springbootapi
spec:
  selector:
    app: springbootapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
